import{a as x,S as P,i}from"./assets/vendor-73qhTu8_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function g(o,t=1){const{data:s}=await x("https://pixabay.com/api/",{params:{key:"55787535-61c82cd2300b887fd2ca60733",q:o,per_page:15,page:t,image_type:"photo",orientation:"horizontal",safesearch:!0}});return s}let m=null;function p(o){const t=o.map(({webformatURL:a,largeImageURL:e,tags:r,likes:n,views:S,comments:q,downloads:v})=>`<li class='gallery-item'>
        <a  href="${e}">
        <img  src="${a}" alt="${r}"/></a>
        <ul class="gallery-text-list">
        <li class='gallery-item-text'><h2>Likes</h2>
        <p> ${n}</p></li>
        <li class='gallery-item-text'>
        <h2>Views</h2>
        <p>${S}</p></li>
        <li class='gallery-item-text'>
        <h2>Comments</h2>
        <p>${q}</p></li>
        <li class='gallery-item-text'>
        <h2>Downloads</h2>
        <p>${v}</p></li></ul>
            </li > `).join(""),s=document.querySelector(".gallery");s&&(s.insertAdjacentHTML("beforeend",t),m?m.refresh():m=new P(".gallery a",{captionsData:"alt",captionDelay:250}))}function $(){const o=document.querySelector(".gallery");o&&(o.innerHTML="")}const d=document.querySelector(".loader");function b(){d&&d.classList.add("visible")}function L(){d&&d.classList.remove("visible")}const h=document.querySelector(".button-load-more");function w(){h&&h.classList.remove("load-more-hidden")}function c(){h&&h.classList.add("load-more-hidden")}const M=document.querySelector(".form"),f=document.querySelector(".button-load-more");M.addEventListener("submit",O);f.addEventListener("click",B);let l=1,u="",y=0;const R=15;c();async function O(o){if(o.preventDefault(),l=1,u=o.target.elements["search-text"].value.trim(),$(),c(),!u){i.show({color:"red",position:"topRight",message:"Please enter your request!"});return}b();try{const{hits:t,totalHits:s}=await g(u,l);if(t.length==0){i.show({color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(t),y=Math.ceil(s/R),l<y?w():(c(),i.show({color:"blue",position:"topRight",message:" We're sorry, but you've reached the end of search results."}))}catch{i.show({color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}finally{L(),o.target.reset()}}async function B(o){l++,f.disabled=!0,c(),b();try{const t=await g(u,l);p(t.hits),l>=y?(c(),i.show({color:"blue",position:"topRight",message:" We're sorry, but you've reached the end of search results."})):w();const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}catch{i.show({color:"red",position:"topRight",message:"Sorry, there are no images."})}finally{L(),f.disabled=!1}}
//# sourceMappingURL=index.js.map
